[package]
name = "bah"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-channel = "2.5"
chrono = { version = "0.4", default-features = true }
env_logger = "0.11"
gpui = { git = "https://github.com/4rna-y/zed", rev = "f005b687a4287536540fe71b898fe63a176ed0d3", default-features = false, features = ["wayland"] }
gpui_platform = { git = "https://github.com/4rna-y/zed", rev = "f005b687a4287536540fe71b898fe63a176ed0d3", default-features = false, features = ["wayland"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
zbus = "5.18"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
